### ISSUE TITLE
Arrays are not allowed in class constants

### ISSUE THREAD

**Issue by sayajin101** [jayankaghosh/phpcaller#1]
[root@localhost opl]# php truecaller search 9876543210
PHP Fatal error:  Arrays are not allowed in class constants in /var/www/html/opl/bin/Helper.php on line 11

Fatal error: Arrays are not allowed in class constants in /var/www/html/opl/bin/Helper.php on line 11

**Comment by jayankaghosh** [comment]
Which PHP version are you using?

**Comment by sayajin101** [comment]
Centos 7, PHP 5.4.16

**Comment by jayankaghosh** [comment]
Unfortunately only php5.6 version 5.6+ is allowed
